#!/usr/bin/env python
# bash 1-liner version (much slower)
# MAXLENGTH=10 ; sort -R /usr/share/dict/words | grep -ow -E "[[:lower:]]{1,$MAXLENGTH}" | head -n 4 | xargs echo

import random, string

MAXWORDLENGTH = 10
MINWORDLENGTH = 3
HOWMANYWORDS = 4
SOURCE = "/usr/share/dict/words"

fh = open(SOURCE, "r")
words = string.split(fh.read())
random.shuffle(words)

ct = 0
phrase = ""

while ct < HOWMANYWORDS:
    word = words.pop()
    if len(word) <= MAXWORDLENGTH and len(word) >= MINWORDLENGTH and word.islower() :
        if len(phrase) == 0 :
            phrase = word
        else :
            phrase = phrase + " " + word
        ct+=1

print phrase

