#!/bin/bash

DIR=~/Documents/.yumbackup

[ -d $DIR ] || mkdir $DIR
cp -r /etc/yum.repos.d $DIR
rpm -qa > $DIR/rpmqa
rpm -qa --queryformat "%{NAME}\n" > $DIR/rpmqa_name
rpm -qa --queryformat "%{NAME}.%{ARCH}\n" > $DIR/rpmqa_name.arch
